version: "3.8"
services:
  mysql:
    image: mysql:8.0
    platform: linux/amd64 # 맥북 환경에서 필요한 옵션입니다. pc 환경에서는 제거하시면됩니다.
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./data:/var/lib/mysql
      - ./mysql_schema:/home/
      - ./init_db/init.sql:/docker-entrypoint-initdb.d/setup.sql
    ports:
      - "3306:3306"
      - protocol: tcp
    user: "1001"
  redis:
    image: redis:6.2
    platform: linux/amd64 # 맥북 환경에서 필요한 옵션입니다. pc 환경에서는 제거하시면됩니다.
    command: redis-server --port 6379
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - "6379:6379"
